<a href="https://colab.research.google.com/github/Julianfried/Diplomatura-en-IA-Instituto-Humai/blob/main/Matematicas%20para%20IA/Ejercicios_vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios en vivo - clase 1 Matematica para IA

In [4]:
import numpy as np
import matplotlib.pyplot as plt

## 1) Realizar operaciones con vectores
A partir de los vectores `u`, `v` y `t`

1. Calcular el vector opuesto a `v` y llamarlo `w`
2. Realizar la suma `u` + `t` + `t`
3. Realizar la suma `u` + 2 `t`
4. Obtener el vector normalizado de `v` y `w`

In [5]:
u = np.array([3, 5, 1])
v = np.array([-4, 2, 4])
t = np.array([7, 8, 3])

In [6]:
#1
w=v*-1
print(w)

[ 4 -2 -4]


In [7]:
#2
u + t + t

array([17, 21,  7])

In [8]:
#3
u+(2*t)

array([17, 21,  7])

In [10]:
#4
import numpy.linalg as LA
v_norm = u/LA.norm(u)
w_norm = w/LA.norm(w)
print(v_norm)
print(w_norm)

[0.50709255 0.84515425 0.16903085]
[ 0.66666667 -0.33333333 -0.66666667]


## 2) Calcular proyecciones de vectores
Utilizando alguna de las siguientes formulas equivalentes:

$\textbf{proj}_{\textbf{u}}{\textbf{v}} = \dfrac{\textbf{u} \cdot \textbf{v}}{\left \Vert \textbf{u} \right \| ^2} \times \textbf{u}$

$\textbf{proj}_{\textbf{u}}{\textbf{v}} = (\textbf{v} \cdot \hat{\textbf{u}}) \times \hat{\textbf{u}}$

Obtener:
- Proyeccion de `u` en `t`:
$\textbf{proj}_{\textbf{t}}{\textbf{u}}$
- Proyeccion de `t` en `v`:
$\textbf{proj}_{\textbf{v}}{\textbf{t}}$

In [17]:
def formula(vector1,vector2):
  return (np.dot(vector1,vector2)/((LA.norm(vector1))**2))*vector1
  

In [18]:
print(formula(u,t))
print(formula(t,v))

[5.48571429 9.14285714 1.82857143]
[0. 0. 0.]


## 3) Crear una funcion `son_paralelos` entre dos vectores
Dos vectores son paralelos si cuentan con una direccion, sin necesidad de tener el mismo sentido.
- A partir de la definicion de producto vectorial: $\textbf{u} \times \textbf{v} = \left \Vert \textbf{u} \right \| \times \left \Vert \textbf{v} \right \| \times sen(\theta)$


Es decir que si se conoce que `u` y `v` no son vectores nulos, si $\textbf{u} \times \textbf{v} = 0$, entonces $sen(\theta) = 0$. El angulo que hace 0 el seno es $2π$ y 0 (angulo de vectores paralelos).




In [19]:
def son_paralelos(u, v):
  cos_theta = u.dot(v) / LA.norm(u) / LA.norm(v)
  theta = np.arccos(np.clip(cos_theta, -1, 1))
  return np.sin(theta)
son_paralelos(u,v)


0.9984114366459335