<a href="https://colab.research.google.com/github/Julianfried/Diplomatura-en-IA-Instituto-Humai/blob/main/Matematicas%20para%20IA/ejercicios_matrices_clase_vivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios en vivo - clase 2 Matematica para IA

In [1]:
import numpy as np

A = np.array([
    [25,20,54],
    [33, 7,14]
])

B = np.array([
    [34,50],
    [40,20],
    [23,47]
])

C = np.array([
        [ 2,  3, -8],
        [ 0, 17,-19],
        [ 0,  0, 31]
])

D = np.array([
        [37, 29,  7],
        [29, 17, 19],
        [ 7, 19, 37]
    ])

## 1) Clasificar las matrices A, B, C y D
Puede haber más de una opción correcta, así como ninguna opción correcta.

In [2]:
#@markdown Matriz A
Cuadrada_A = False #@param {type:"boolean"}
Simetrica_A = False #@param {type:"boolean"}
Triangular_Superior_A = False #@param {type:"boolean"}
Triangular_Inferior_A = False #@param {type:"boolean"}
res_A = [Cuadrada_A, Simetrica_A, Triangular_Superior_A, Triangular_Inferior_A]

#@markdown Matriz B
Cuadrada_B = False #@param {type:"boolean"}
Simetrica_B = False #@param {type:"boolean"}
Triangular_Superior_B = False #@param {type:"boolean"}
Triangular_Inferior_B = False #@param {type:"boolean"}

#@markdown Matriz C
Cuadrada_C = True #@param {type:"boolean"}
Simetrica_C = False #@param {type:"boolean"}
Triangular_Superior_C = True #@param {type:"boolean"}
Triangular_Inferior_C = False #@param {type:"boolean"}

#@markdown Matriz D
Cuadrada_D = True #@param {type:"boolean"}
Simetrica_D = True #@param {type:"boolean"}
Triangular_Superior_D = False #@param {type:"boolean"}
Triangular_Inferior_D = False #@param {type:"boolean"}

In [3]:
#@markdown ###Respuestas
print('La matriz A no cumple ninguna de las clasificaciones')
print('La matriz B no cumple ninguna de las clasificaciones')
print('La matriz C es una matriz cuadrada y triangular superior')
print('La matriz D es una matriz cuadrada y simetrica')

La matriz A no cumple ninguna de las clasificaciones
La matriz B no cumple ninguna de las clasificaciones
La matriz C es una matriz cuadrada y triangular superior
La matriz D es una matriz cuadrada y simetrica


## 2) Obtener la transpuesta de B y C
Guardar la transpuesta de `C` en `E`

In [6]:
E = C.T
b = B.T
print(E)


[[  2   0   0]
 [  3  17   0]
 [ -8 -19  31]]


## 3) Realizar las siguientes operaciones

- $2 \cdot C + 2D$
- $2 \cdot (C + D)$
- $3C + 4E$

In [7]:
C = np.array([
        [ 2,  3, -8],
        [ 0, 17,-19],
        [ 0,  0, 31]
])

D = np.array([
        [37, 29,  7],
        [29, 17, 19],
        [ 7, 19, 37]
    ])

In [8]:
resultado1 = 2*C + 2*D

resultado2 = 2*(C+D)

resultado3 = 3*C + 4*E

print("2*C + 2*D:")
print(resultado1)

print("2*(C + D):")
print(resultado2)

print("3*C + 4*E:")
print(resultado3)


2*C + 2*D:
[[ 78  64  -2]
 [ 58  68   0]
 [ 14  38 136]]
2*(C + D):
[[ 78  64  -2]
 [ 58  68   0]
 [ 14  38 136]]
3*C + 4*E:
[[ 14   9 -24]
 [ 12 119 -57]
 [-32 -76 217]]


## Respuestas:

Dimensiones de las matrices:
A: Dimensión (2 x 3)
B: Dimensión (3 x 2)
C: Dimensión (3 x 3)
D: Dimensión (3 x 3)

F=AB  ¿Se puede realizar esta operacion?
Esta operación se puede realizar si el número de columnas de A coincide con el número de filas de B. Por lo tanto, se puede realizar la multiplicación.

G=BA  ¿Se puede realizar esta operacion?
Esta operación no se puede realizar. El número de columnas de B es distinto al de filas de A.

H=A(DTC)  ¿Se puede realizar esta operacion?
Esta operación se puede realizar si el número de columnas de A coincide con el número de filas de DTC. Como $D^TC$ resulta en una matriz de (3x3), el número de filas coincide con el número de columnas de A. Por lo tanto, se puede realizar la multiplicación.

## 4) Completar la implementacion de la funcion obtener_diagonal(), solo si la matriz es cuadrada

In [9]:
def obtener_diagonal(A):
  filas, columnas = A.shape

  if filas==columnas:
    diagonal = np.zeros(filas)
    for i in range(filas):
      diagonal[i] = A[i,i]
    return diagonal

  return None

print('Matriz C:')
print(C)
print('Diagonal de C:')
print(obtener_diagonal(C))

Matriz C:
[[  2   3  -8]
 [  0  17 -19]
 [  0   0  31]]
Diagonal de C:
[ 2. 17. 31.]


## 5) Completar la implementacion de las funciones permite_inversa() y obtener_inversa()
Para obtener la inversa se debe verificar que la matriz admite inversa. Si es posible, devolver la inversa, sino generar un ValueError.

**Nota:** una matriz es inversible si su determinante es distinto de 0, estas matrices se llaman no singulares o regulares.

In [10]:
def permite_inversa(A):
  det_A = np.linalg.det(A)
  return det_A != 0

def obtener_inversa(A):
  if permite_inversa(A):
    inversa = np.linalg.inv(A)
    return inversa
  else:
    raise ValueError("La matriz no admite inversa")